import { Link } from 'react-router-dom'
import styles from './ServiceDetail.module.css'

function HerniaSurgery() {
  return (
    <>
      <section className={styles.serviceHero}><div className={`contenedor ${styles.serviceHeroGrid}`}><div><span className={styles.serviceEyebrow}>Cirugía General · Tijuana</span><h1>Cirugía de<br />hernia</h1></div><div className={styles.serviceHeroMeta}><div className={styles.areaCount}><span>Área de atención</span><strong>02 <i>/ 05</i></strong></div><p>Información para la valoración de hernias con el Dr. Edwin García Garrido, Cirujano General.</p></div></div><span className={styles.serviceHeroRing} aria-hidden="true" /></section>

      <section className={`${styles.serviceIntro} seccion`}><div className={`contenedor ${styles.serviceIntroGrid}`}><div className={styles.serviceIntroCopy}><span className={styles.sectionLabel}>Cirugía General</span><h2>¿Qué es una hernia?</h2><p>Una hernia ocurre cuando tejido u otro contenido protruye a través de una zona debilitada de la pared que normalmente lo contiene. Entre las hernias de la pared abdominal se encuentran la inguinal y la umbilical.</p><div className={styles.symptomBlock}><span className={styles.blockNumber}>01</span><div><h3>¿Qué molestias pueden motivar una valoración?</h3><p>Puede aparecer un bulto o aumento de volumen, molestia, presión o dolor que cambia con el esfuerzo o ciertas actividades. La presentación varía entre pacientes y la exploración médica ayuda a identificar el problema.</p></div></div></div><figure className={styles.editorialFigure}><div className={styles.figureFrame}><div className={styles.figureOrbit} aria-hidden="true"><i /></div><div className={styles.figurePlaceholder} role="img" aria-label="Pared abdominal y hernia"><span>Ilustración médica</span><strong>Pared abdominal y hernia</strong></div><span className={styles.figureCross} aria-hidden="true">+</span></div><figcaption>Esquema de una hernia de la pared abdominal.</figcaption></figure></div><div className={`contenedor ${styles.urgentNote}`}><span className={styles.urgentMark}>!</span><div><strong>¿Cuándo buscar atención urgente?</strong><p>Dolor intenso o repentino, un bulto que cambia de aspecto o no se reduce, vómitos o deterioro importante requieren atención médica oportuna. Una cita programada no sustituye un servicio de urgencias.</p></div></div></section>

      <section className={`${styles.serviceInfo} seccion`}><div className="contenedor"><div className={styles.serviceInfoHead}><span className={styles.sectionLabel}>Valoración y manejo</span><h2>Tres momentos de la valoración</h2></div><div className={styles.clinicalPath}><span className={styles.pathLine} aria-hidden="true" />
            <article className={styles.serviceStep}><div className={styles.pathMarker}><i /><span>01</span></div><span className={styles.stepLabel}>Exploración</span><h3>¿Cómo se diagnostica?</h3><p>La valoración suele incluir los síntomas, antecedentes y exploración física. Dependiendo del caso, pueden utilizarse estudios de imagen para complementar la evaluación.</p></article>
            <article className={styles.pathFocus}><div className={styles.pathMarker}><i /><span>02</span></div><span className={styles.pathLabel}>Decisión individual</span><h3>¿Cuándo puede considerarse cirugía?</h3><p>La decisión depende del tipo de hernia, síntomas, exploración, evolución y características individuales. No todas las hernias se manejan exactamente de la misma forma.</p></article>
            <article className={styles.serviceStep}><div className={styles.pathMarker}><i /><span>03</span></div><span className={styles.stepLabel}>Reparación</span><h3>¿En qué consiste la reparación?</h3><p>El objetivo de la cirugía es reparar el defecto de la pared. La técnica y el abordaje apropiados se seleccionan de acuerdo con las características de cada caso.</p></article>
          </div></div></section>

      <section className={`${styles.editorialFaq} seccion`}><div className={`contenedor ${styles.editorialFaqGrid}`}><div className={styles.faqIntro}><span className={styles.sectionLabel}>Preguntas frecuentes</span><h2>Dudas comunes sobre hernias</h2><p>Información general para pacientes en proceso de valoración.</p><span className={styles.faqGraphic} aria-hidden="true">?</span></div><div className={styles.editorialFaqs}>
            <details><summary>¿Una hernia puede desaparecer sola?</summary><p>En adultos, una hernia de la pared abdominal generalmente no se corrige por sí sola; su manejo depende de la valoración individual.</p></details>
            <details><summary>¿Todas las hernias necesitan operarse de inmediato?</summary><p>No necesariamente. El momento y la necesidad de una cirugía dependen del tipo de hernia, síntomas y valoración médica.</p></details>
            <details><summary>¿Qué tipos de hernia atiende Cirugía General?</summary><p>Las hernias de la pared abdominal, como la inguinal y la umbilical, forman parte de los problemas que puede valorar Cirugía General.</p></details>
            <details><summary>¿Debo llevar estudios previos?</summary><p>Si ya cuentas con estudios relacionados con la hernia, pueden ser útiles durante la consulta.</p></details>
          </div></div></section>

      <section className={styles.serviceConsult}><div className={`contenedor ${styles.serviceConsultGrid}`}><div><span className={styles.serviceEyebrow}>Consulta de Cirugía General</span><h2>Valoración de hernia<br />en Tijuana</h2></div><div className={styles.consultCopy}><p>El Dr. Edwin García Garrido brinda consulta privada en Torre Médica Otay, Tijuana, para valorar cada caso y explicar las alternativas de manejo de acuerdo con el diagnóstico.</p><div className={styles.consultActions}><Link to="/contacto" className={styles.consultButton}>Consultar disponibilidad</Link><Link to="/dr-edwin-garcia-garrido">Conocer trayectoria →</Link></div></div></div></section>

      <nav className={styles.serviceNav} aria-label="Navegación entre áreas de atención"><div className={`contenedor ${styles.serviceNavInner}`}><Link to="/cirugia-de-vesicula">← Vesícula</Link><Link to="/cirugia-de-tiroides"><span>Siguiente área · 03 / 05</span><strong>Tiroides →</strong></Link></div></nav>
      <div className={`contenedor ${styles.serviceDisclaimer}`}>Información general para pacientes. Este contenido no sustituye una valoración médica individual.</div>
    </>
  )
}
export default HerniaSurgery
