import { Link } from 'react-router-dom'
import styles from './ServiceDetail.module.css'

function HerniaSurgery() {
  return (
    <>
      <section className={styles.hero}><div className="contenedor"><span className={styles.eyebrow}>Cirugía General · Tijuana</span><h1 className={styles.titulo}>Cirugía de hernia en Tijuana</h1><p className={styles.resumen}>Información sobre valoración de hernias y consulta con el Dr. Edwin García Garrido, Cirujano General.</p></div></section>
      <section className={`${styles.bloque} seccion`}><div className="contenedor">
        <div className={styles.introGrid}><div>
          <h2 className={styles.encabezado}>¿Qué es una hernia?</h2><p className={styles.parrafo}>Una hernia ocurre cuando tejido u otro contenido protruye a través de una zona debilitada de la pared que normalmente lo contiene. Entre las hernias de la pared abdominal se encuentran la inguinal y la umbilical.</p>
          <h2 className={styles.encabezado}>¿Qué molestias pueden motivar una valoración?</h2><p className={styles.parrafo}>Puede aparecer un bulto o aumento de volumen, molestia, presión o dolor que cambia con el esfuerzo o ciertas actividades. La presentación varía entre pacientes y la exploración médica ayuda a identificar el problema.</p>
          <aside className={styles.alerta}><strong>¿Cuándo buscar atención urgente?</strong><p>Dolor intenso o repentino, un bulto que cambia de aspecto o no se reduce, vómitos o deterioro importante requieren atención médica oportuna. Una cita programada no sustituye un servicio de urgencias.</p></aside>
        </div><figure className={styles.figuraMedica}><div className={styles.imagenPlaceholder} role="img" aria-label="Pared abdominal y hernia"><span>Ilustración médica</span><strong>Pared abdominal y hernia</strong></div><figcaption>Esquema de una hernia de la pared abdominal.</figcaption></figure></div>
        <div className={styles.infoGrid}><article className={styles.infoItem}><h2>¿Cómo se diagnostica?</h2><p>La valoración suele incluir los síntomas, antecedentes y exploración física. Dependiendo del caso, pueden utilizarse estudios de imagen para complementar la evaluación.</p></article><article className={styles.infoItem}><h2>¿Cuándo puede considerarse cirugía?</h2><p>La decisión depende del tipo de hernia, síntomas, exploración, evolución y características individuales. No todas las hernias se manejan exactamente de la misma forma.</p></article><article className={styles.infoItem}><h2>¿En qué consiste la reparación?</h2><p>El objetivo de la cirugía es reparar el defecto de la pared. La técnica y el abordaje apropiados se seleccionan de acuerdo con las características de cada caso.</p></article></div>
        <section className={styles.faqSection}><div className={styles.faqIntro}><span className={styles.sectionLabel}>Preguntas frecuentes</span><h2>Dudas comunes sobre las hernias</h2><p>Respuestas generales sobre valoración y tratamiento quirúrgico.</p></div><div className={styles.faqs}><details className={styles.faq}><summary>¿Una hernia puede desaparecer sola?</summary><p>En adultos, una hernia de la pared abdominal generalmente no se corrige por sí sola; su manejo depende de la valoración individual.</p></details><details className={styles.faq}><summary>¿Todas las hernias necesitan operarse de inmediato?</summary><p>No necesariamente. El momento y la necesidad de una cirugía dependen del tipo de hernia, síntomas y valoración médica.</p></details><details className={styles.faq}><summary>¿Qué tipos de hernia atiende Cirugía General?</summary><p>Las hernias de la pared abdominal, como la inguinal y la umbilical, forman parte de los problemas que puede valorar Cirugía General.</p></details><details className={styles.faq}><summary>¿Debo llevar estudios previos?</summary><p>Si ya cuentas con estudios relacionados con la hernia, pueden ser útiles durante la consulta.</p></details></div></section>
        <section className={styles.valoracion}><div className={styles.valoracionTexto}><span className={styles.sectionLabel}>Consulta de Cirugía General</span><h2>Valoración de hernia en Tijuana</h2><p>El Dr. Edwin García Garrido brinda consulta privada en Torre Médica Otay, Tijuana, para valorar cada caso y explicar las alternativas de manejo de acuerdo con el diagnóstico.</p></div><div className={styles.valoracionAcciones}><Link to="/contacto" className={styles.boton}>Agendar valoración</Link><Link to="/dr-edwin-garcia-garrido" className={styles.enlace}>Conocer al Dr. Edwin García Garrido →</Link></div></section>
        <p className={styles.revision}>Información general para pacientes. Este contenido no sustituye una valoración médica individual.</p>
      </div></section>
    </>
  )
}
export default HerniaSurgery
