import { Link } from 'react-router-dom'
import styles from './ServiceDetail.module.css'

function LipomaSurgery() {
  return (
    <>
      <section className={styles.serviceHero}><div className={`contenedor ${styles.serviceHeroGrid}`}><div><span className={styles.serviceEyebrow}>Cirugía General · Tijuana</span><h1>Valoración de<br />lipomas</h1></div><div className={styles.serviceHeroMeta}><div className={styles.areaCount}><span>Área de atención</span><strong>04 <i>/ 05</i></strong></div><p>Información para la valoración de lipomas con el Dr. Edwin García Garrido, Cirujano General.</p></div></div><span className={styles.serviceHeroRing} aria-hidden="true" /></section>

      <section className={`${styles.serviceIntro} seccion`}><div className={`contenedor ${styles.serviceIntroGrid}`}><div className={styles.serviceIntroCopy}><span className={styles.sectionLabel}>Cirugía General</span><h2>¿Qué es un lipoma?</h2><p>Un lipoma es una masa de tejido graso que suele localizarse debajo de la piel. Existen otros tipos de bultos o lesiones de tejidos blandos, por lo que una valoración permite orientar el diagnóstico antes de decidir una extirpación.</p><div className={styles.symptomBlock}><span className={styles.blockNumber}>01</span><div><h3>¿Cuándo conviene valorar un bulto?</h3><p>Un aumento de volumen nuevo, que crece, produce molestias, cambia o genera dudas sobre su origen merece valoración médica. No todo bulto debajo de la piel es necesariamente un lipoma.</p></div></div></div><figure className={styles.editorialFigure}><div className={styles.figureFrame}><div className={styles.figureOrbit} aria-hidden="true"><i /></div><div className={styles.figurePlaceholder} role="img" aria-label="Lipoma y tejido subcutáneo"><span>Ilustración médica</span><strong>Lipoma y tejido subcutáneo</strong></div><span className={styles.figureCross} aria-hidden="true">+</span></div><figcaption>Esquema de un lipoma localizado bajo la piel.</figcaption></figure></div><div className={`contenedor ${styles.urgentNote}`}><span className={styles.urgentMark}>!</span><div><strong>Consulta antes de decidir una extirpación</strong><p>La valoración previa permite revisar localización, tamaño, características y antecedentes para determinar si es apropiado retirar la lesión y qué manejo requiere.</p></div></div></section>

      <section className={`${styles.serviceInfo} seccion`}><div className="contenedor"><div className={styles.serviceInfoHead}><span className={styles.sectionLabel}>Valoración y manejo</span><h2>Tres momentos de la valoración</h2></div><div className={styles.clinicalPath}><span className={styles.pathLine} aria-hidden="true" />
            <article className={styles.serviceStep}><div className={styles.pathMarker}><i /><span>01</span></div><span className={styles.stepLabel}>Valoración</span><h3>¿Cómo se valora un lipoma?</h3><p>La consulta incluye antecedentes y exploración de la lesión. Dependiendo de sus características, el médico puede considerar si se requieren estudios adicionales.</p></article>
            <article className={styles.pathFocus}><div className={styles.pathMarker}><i /><span>02</span></div><span className={styles.pathLabel}>Indicación</span><h3>¿Cuándo puede retirarse?</h3><p>La indicación de extirpación depende de factores como molestias, crecimiento, localización, características de la lesión y diagnóstico.</p></article>
            <article className={styles.serviceStep}><div className={styles.pathMarker}><i /><span>03</span></div><span className={styles.stepLabel}>Procedimiento</span><h3>¿Cómo se realiza la extirpación?</h3><p>El procedimiento depende del tamaño, profundidad y ubicación de la lesión. La técnica y el entorno apropiados se determinan después de valorarla.</p></article>
          </div></div></section>

      <section className={`${styles.editorialFaq} seccion`}><div className={`contenedor ${styles.editorialFaqGrid}`}><div className={styles.faqIntro}><span className={styles.sectionLabel}>Preguntas frecuentes</span><h2>Dudas comunes sobre lipomas</h2><p>Información general para pacientes en proceso de valoración.</p><span className={styles.faqGraphic} aria-hidden="true">?</span></div><div className={styles.editorialFaqs}>
            <details><summary>¿Todos los lipomas necesitan retirarse?</summary><p>No. La necesidad de extirpación depende de las características de la lesión, síntomas y valoración médica.</p></details>
            <details><summary>¿Todo bulto debajo de la piel es un lipoma?</summary><p>No. Diferentes lesiones pueden producir un aumento de volumen, por eso es importante confirmar la naturaleza del bulto.</p></details>
            <details><summary>¿Se necesita algún estudio antes de retirarlo?</summary><p>Depende de las características de la lesión. La valoración médica determina si hacen falta estudios adicionales.</p></details>
            <details><summary>¿Puedo agendar directamente para retirarlo?</summary><p>Lo apropiado es realizar primero una valoración para confirmar el diagnóstico y planear el manejo adecuado.</p></details>
          </div></div></section>

      <section className={styles.serviceConsult}><div className={`contenedor ${styles.serviceConsultGrid}`}><div><span className={styles.serviceEyebrow}>Consulta de Cirugía General</span><h2>Valoración de lipomas<br />en Tijuana</h2></div><div className={styles.consultCopy}><p>El Dr. Edwin García Garrido brinda consulta privada en Torre Médica Otay para valorar lipomas y otras lesiones que puedan requerir manejo quirúrgico.</p><div className={styles.consultActions}><Link to="/contacto" className={styles.consultButton}>Consultar disponibilidad</Link><Link to="/dr-edwin-garcia-garrido">Conocer trayectoria →</Link></div></div></div></section>

      <nav className={styles.serviceNav} aria-label="Navegación entre áreas de atención"><div className={`contenedor ${styles.serviceNavInner}`}><Link to="/cirugia-de-tiroides">← Tiroides</Link><Link to="/trauma-y-urgencias"><span>Siguiente área · 05 / 05</span><strong>Trauma y urgencias →</strong></Link></div></nav>
      <div className={`contenedor ${styles.serviceDisclaimer}`}>Información general para pacientes. Este contenido no sustituye una valoración médica individual.</div>
    </>
  )
}
export default LipomaSurgery
