import { Link } from 'react-router-dom'
import styles from './ServiceDetail.module.css'

function LipomaSurgery() {
  return (
    <>
      <section className={styles.hero}><div className="contenedor"><span className={styles.eyebrow}>Cirugía General · Tijuana</span><h1 className={styles.titulo}>Valoración y cirugía de lipomas en Tijuana</h1><p className={styles.resumen}>Información sobre valoración de lipomas y consulta con el Dr. Edwin García Garrido, Cirujano General.</p></div></section>
      <section className={`${styles.bloque} seccion`}><div className="contenedor">
        <div className={styles.introGrid}><div>
          <h2 className={styles.encabezado}>¿Qué es un lipoma?</h2><p className={styles.parrafo}>Un lipoma es una masa de tejido graso que suele localizarse debajo de la piel. Existen otros tipos de bultos o lesiones de tejidos blandos, por lo que una valoración permite orientar el diagnóstico antes de decidir una extirpación.</p>
          <h2 className={styles.encabezado}>¿Cuándo conviene valorar un bulto?</h2><p className={styles.parrafo}>Un aumento de volumen nuevo, que crece, produce molestias, cambia o genera dudas sobre su origen merece valoración médica. No todo bulto debajo de la piel es necesariamente un lipoma.</p>
          <aside className={styles.alerta}><strong>Consulta antes de decidir una extirpación</strong><p>La valoración previa permite revisar localización, tamaño, características y antecedentes para determinar si es apropiado retirar la lesión y qué manejo requiere.</p></aside>
        </div><figure className={styles.figuraMedica}><div className={styles.imagenPlaceholder} role="img" aria-label="Lipoma y tejido subcutáneo"><span>Ilustración médica</span><strong>Lipoma y tejido subcutáneo</strong></div><figcaption>Esquema de un lipoma localizado bajo la piel.</figcaption></figure></div>
        <div className={styles.infoGrid}><article className={styles.infoItem}><h2>¿Cómo se valora un lipoma?</h2><p>La consulta incluye antecedentes y exploración de la lesión. Dependiendo de sus características, el médico puede considerar si se requieren estudios adicionales.</p></article><article className={styles.infoItem}><h2>¿Cuándo puede retirarse?</h2><p>La indicación de extirpación depende de factores como molestias, crecimiento, localización, características de la lesión y diagnóstico.</p></article><article className={styles.infoItem}><h2>¿Cómo se realiza la extirpación?</h2><p>El procedimiento depende del tamaño, profundidad y ubicación de la lesión. La técnica y el entorno apropiados se determinan después de valorarla.</p></article></div>
        <section className={styles.faqSection}><div className={styles.faqIntro}><span className={styles.sectionLabel}>Preguntas frecuentes</span><h2>Dudas comunes sobre los lipomas</h2><p>Información general sobre valoración y posible extirpación.</p></div><div className={styles.faqs}><details className={styles.faq}><summary>¿Todos los lipomas necesitan retirarse?</summary><p>No. La necesidad de extirpación depende de las características de la lesión, síntomas y valoración médica.</p></details><details className={styles.faq}><summary>¿Todo bulto debajo de la piel es un lipoma?</summary><p>No. Diferentes lesiones pueden producir un aumento de volumen, por eso es importante confirmar la naturaleza del bulto.</p></details><details className={styles.faq}><summary>¿Se necesita algún estudio antes de retirarlo?</summary><p>Depende de las características de la lesión. La valoración médica determina si hacen falta estudios adicionales.</p></details><details className={styles.faq}><summary>¿Puedo agendar directamente para retirarlo?</summary><p>Lo apropiado es realizar primero una valoración para confirmar el diagnóstico y planear el manejo adecuado.</p></details></div></section>
        <section className={styles.valoracion}><div className={styles.valoracionTexto}><span className={styles.sectionLabel}>Consulta de Cirugía General</span><h2>Valoración de lipomas en Tijuana</h2><p>El Dr. Edwin García Garrido brinda consulta privada en Torre Médica Otay para valorar lipomas y otras lesiones que puedan requerir manejo quirúrgico.</p></div><div className={styles.valoracionAcciones}><Link to="/contacto" className={styles.boton}>Agendar valoración</Link><Link to="/dr-edwin-garcia-garrido" className={styles.enlace}>Conocer al Dr. Edwin García Garrido →</Link></div></section>
        <p className={styles.revision}>Información general para pacientes. Este contenido no sustituye una valoración médica individual.</p>
      </div></section>
    </>
  )
}
export default LipomaSurgery
