import { Link } from 'react-router-dom'
import styles from './ServiceDetail.module.css'

function ThyroidSurgery() {
  return (
    <>
      <section className={styles.serviceHero}><div className={`contenedor ${styles.serviceHeroGrid}`}><div><span className={styles.serviceEyebrow}>Cirugía General · Tijuana</span><h1>Cirugía de<br />tiroides</h1></div><div className={styles.serviceHeroMeta}><div className={styles.areaCount}><span>Área de atención</span><strong>03 <i>/ 05</i></strong></div><p>Información para la valoración de tiroides con el Dr. Edwin García Garrido, Cirujano General.</p></div></div><span className={styles.serviceHeroRing} aria-hidden="true" /></section>

      <section className={`${styles.serviceIntro} seccion`}><div className={`contenedor ${styles.serviceIntroGrid}`}><div className={styles.serviceIntroCopy}><span className={styles.sectionLabel}>Cirugía General</span><h2>Valoración quirúrgica de la tiroides</h2><p>La tiroides es una glándula localizada en la parte anterior del cuello. Algunos nódulos, aumentos de tamaño u otros padecimientos pueden requerir valoración para determinar si existe una indicación quirúrgica.</p><div className={styles.symptomBlock}><span className={styles.blockNumber}>01</span><div><h3>¿Qué hallazgos pueden llevar a una valoración?</h3><p>Un nódulo tiroideo, crecimiento de la glándula, cambios visibles en el cuello o estudios previos con hallazgos que requieren seguimiento pueden ser motivos de valoración. Tener un nódulo no significa automáticamente necesitar cirugía.</p></div></div></div><figure className={styles.editorialFigure}><div className={styles.figureFrame}><div className={styles.figureOrbit} aria-hidden="true"><i /></div><div className={styles.figurePlaceholder} role="img" aria-label="Tiroides y anatomía del cuello"><span>Ilustración médica</span><strong>Tiroides y anatomía del cuello</strong></div><span className={styles.figureCross} aria-hidden="true">+</span></div><figcaption>Ubicación anatómica de la glándula tiroides.</figcaption></figure></div><div className={`contenedor ${styles.urgentNote}`}><span className={styles.urgentMark}>!</span><div><strong>Atención médica oportuna</strong><p>Dificultad importante para respirar o tragar, especialmente si aparece o empeora de forma aguda, requiere atención médica oportuna. Una consulta programada no sustituye un servicio de urgencias.</p></div></div></section>

      <section className={`${styles.serviceInfo} seccion`}><div className="contenedor"><div className={styles.serviceInfoHead}><span className={styles.sectionLabel}>Valoración y manejo</span><h2>Tres momentos de la valoración</h2></div><div className={styles.clinicalPath}><span className={styles.pathLine} aria-hidden="true" />
            <article className={styles.serviceStep}><div className={styles.pathMarker}><i /><span>01</span></div><span className={styles.stepLabel}>Estudios</span><h3>¿Cómo se estudia la tiroides?</h3><p>La evaluación depende del caso y puede integrar exploración, ultrasonido, análisis de laboratorio y resultados de estudios previos. Algunos nódulos requieren estudios adicionales antes de decidir un tratamiento.</p></article>
            <article className={styles.pathFocus}><div className={styles.pathMarker}><i /><span>02</span></div><span className={styles.pathLabel}>Criterio quirúrgico</span><h3>¿Cuándo se valora una cirugía?</h3><p>La cirugía puede considerarse en situaciones específicas según los síntomas, tamaño, características de los estudios y diagnóstico. La decisión debe individualizarse.</p></article>
            <article className={styles.serviceStep}><div className={styles.pathMarker}><i /><span>03</span></div><span className={styles.stepLabel}>Planeación</span><h3>¿Qué se revisa antes de operar?</h3><p>Antes de indicar un procedimiento se revisan el diagnóstico, los estudios disponibles, antecedentes y condiciones del paciente para explicar las opciones y el alcance de la cirugía.</p></article>
          </div></div></section>

      <section className={`${styles.editorialFaq} seccion`}><div className={`contenedor ${styles.editorialFaqGrid}`}><div className={styles.faqIntro}><span className={styles.sectionLabel}>Preguntas frecuentes</span><h2>Dudas comunes sobre tiroides</h2><p>Información general para pacientes en proceso de valoración.</p><span className={styles.faqGraphic} aria-hidden="true">?</span></div><div className={styles.editorialFaqs}>
            <details><summary>¿Todos los nódulos tiroideos necesitan cirugía?</summary><p>No. Muchos nódulos no requieren tratamiento quirúrgico. La conducta depende de sus características y de la evaluación médica.</p></details>
            <details><summary>¿Un nódulo significa cáncer?</summary><p>No. Un nódulo tiroideo puede tener distintas causas. Su evaluación permite determinar qué estudios o seguimiento son apropiados.</p></details>
            <details><summary>¿Debo llevar mi ultrasonido y laboratorios?</summary><p>Sí, si ya cuentas con estudios relacionados con la tiroides es útil llevarlos a la consulta para su revisión.</p></details>
            <details><summary>¿Cirugía General puede valorar la tiroides?</summary><p>La cirugía de tiroides forma parte del campo quirúrgico y puede requerir valoración por un cirujano según el diagnóstico.</p></details>
          </div></div></section>

      <section className={styles.serviceConsult}><div className={`contenedor ${styles.serviceConsultGrid}`}><div><span className={styles.serviceEyebrow}>Consulta de Cirugía General</span><h2>Valoración quirúrgica de tiroides<br />en Tijuana</h2></div><div className={styles.consultCopy}><p>El Dr. Edwin García Garrido brinda consulta privada en Torre Médica Otay para valorar padecimientos de la tiroides que puedan requerir manejo quirúrgico.</p><div className={styles.consultActions}><Link to="/contacto" className={styles.consultButton}>Consultar disponibilidad</Link><Link to="/dr-edwin-garcia-garrido">Conocer trayectoria →</Link></div></div></div></section>

      <nav className={styles.serviceNav} aria-label="Navegación entre áreas de atención"><div className={`contenedor ${styles.serviceNavInner}`}><Link to="/cirugia-de-hernia">← Hernia</Link><Link to="/lipomas"><span>Siguiente área · 04 / 05</span><strong>Lipomas →</strong></Link></div></nav>
      <div className={`contenedor ${styles.serviceDisclaimer}`}>Información general para pacientes. Este contenido no sustituye una valoración médica individual.</div>
    </>
  )
}
export default ThyroidSurgery
