import { Link } from 'react-router-dom'
import styles from './ServiceDetail.module.css'

function ThyroidSurgery() {
  return (
    <>
      <section className={styles.hero}><div className="contenedor"><span className={styles.eyebrow}>Cirugía General · Tijuana</span><h1 className={styles.titulo}>Cirugía de tiroides en Tijuana</h1><p className={styles.resumen}>Información sobre valoración quirúrgica de padecimientos de la tiroides y consulta con el Dr. Edwin García Garrido, Cirujano General.</p></div></section>
      <section className={`${styles.bloque} seccion`}><div className="contenedor">
        <div className={styles.introGrid}><div>
          <h2 className={styles.encabezado}>Valoración quirúrgica de la tiroides</h2><p className={styles.parrafo}>La tiroides es una glándula localizada en la parte anterior del cuello. Algunos nódulos, aumentos de tamaño u otros padecimientos pueden requerir valoración para determinar si existe una indicación quirúrgica.</p>
          <h2 className={styles.encabezado}>¿Qué hallazgos pueden llevar a una valoración?</h2><p className={styles.parrafo}>Un nódulo tiroideo, crecimiento de la glándula, cambios visibles en el cuello o estudios previos con hallazgos que requieren seguimiento pueden ser motivos de valoración. Tener un nódulo no significa automáticamente necesitar cirugía.</p>
          <aside className={styles.alerta}><strong>Atención médica oportuna</strong><p>Dificultad importante para respirar o tragar, especialmente si aparece o empeora de forma aguda, requiere atención médica oportuna. Una consulta programada no sustituye un servicio de urgencias.</p></aside>
        </div><figure className={styles.figuraMedica}><div className={styles.imagenPlaceholder} role="img" aria-label="Tiroides y anatomía del cuello"><span>Ilustración médica</span><strong>Tiroides y anatomía del cuello</strong></div><figcaption>Ubicación anatómica de la glándula tiroides.</figcaption></figure></div>
        <div className={styles.infoGrid}><article className={styles.infoItem}><h2>¿Cómo se estudia la tiroides?</h2><p>La evaluación depende del caso y puede integrar exploración, ultrasonido, análisis de laboratorio y resultados de estudios previos. Algunos nódulos requieren estudios adicionales antes de decidir un tratamiento.</p></article><article className={styles.infoItem}><h2>¿Cuándo se valora una cirugía?</h2><p>La cirugía puede considerarse en situaciones específicas según los síntomas, tamaño, características de los estudios y diagnóstico. La decisión debe individualizarse.</p></article><article className={styles.infoItem}><h2>¿Qué se revisa antes de operar?</h2><p>Antes de indicar un procedimiento se revisan el diagnóstico, los estudios disponibles, antecedentes y condiciones del paciente para explicar las opciones y el alcance de la cirugía.</p></article></div>
        <section className={styles.faqSection}><div className={styles.faqIntro}><span className={styles.sectionLabel}>Preguntas frecuentes</span><h2>Dudas comunes sobre cirugía de tiroides</h2><p>Información general para pacientes en proceso de valoración.</p></div><div className={styles.faqs}><details className={styles.faq}><summary>¿Todos los nódulos tiroideos necesitan cirugía?</summary><p>No. Muchos nódulos no requieren tratamiento quirúrgico. La conducta depende de sus características y de la evaluación médica.</p></details><details className={styles.faq}><summary>¿Un nódulo significa cáncer?</summary><p>No. Un nódulo tiroideo puede tener distintas causas. Su evaluación permite determinar qué estudios o seguimiento son apropiados.</p></details><details className={styles.faq}><summary>¿Debo llevar mi ultrasonido y laboratorios?</summary><p>Sí, si ya cuentas con estudios relacionados con la tiroides es útil llevarlos a la consulta para su revisión.</p></details><details className={styles.faq}><summary>¿Cirugía General puede valorar la tiroides?</summary><p>La cirugía de tiroides forma parte del campo quirúrgico y puede requerir valoración por un cirujano según el diagnóstico.</p></details></div></section>
        <section className={styles.valoracion}><div className={styles.valoracionTexto}><span className={styles.sectionLabel}>Consulta de Cirugía General</span><h2>Valoración quirúrgica de tiroides en Tijuana</h2><p>El Dr. Edwin García Garrido brinda consulta privada en Torre Médica Otay para valorar padecimientos de la tiroides que puedan requerir manejo quirúrgico.</p></div><div className={styles.valoracionAcciones}><Link to="/contacto" className={styles.boton}>Agendar valoración</Link><Link to="/dr-edwin-garcia-garrido" className={styles.enlace}>Conocer al Dr. Edwin García Garrido →</Link></div></section>
        <p className={styles.revision}>Información general para pacientes. Este contenido no sustituye una valoración médica individual.</p>
      </div></section>
    </>
  )
}
export default ThyroidSurgery
